; Listing generated by MuhammadUsman Non-optimizing Compiler Version <>

TITLE	blah.asm

	.686P 
	.XMM  
	include listing.inc 
	.model	flat 

INCLUDELIB LIBCMT 
INCLUDELIB OLDNAMES 

PUBLIC	_asm_main 
EXTRN	_put:PROC 
EXTRN  _get:PROC 
EXTRN  _mjmalloc:PROC 

_DATA	SEGMENT
BadContravariantParams$$:
	DD 0	;  no base class
	DD _asm_main	;  BadContravariantParams::main
B$$:
	DD 0	;  no base class
	DD B$my	;  B::my

_DATA	ENDS

_TEXT	SEGMENT 

_asm_main PROC	; main
; Line 3
push	ebp
mov	ebp, esp
;  Line: 3
; Line 3
push	ecx
push	12
call	_mjmalloc
add	esp, 4
pop	ecx
lea	edx, B$$
mov	[eax], edx
mov	ecx, eax
mov	eax, 432
push	eax
push	ecx
; Line 3
mov	eax, [ecx]
call	dword ptr [eax+4]
push	ecx
push	eax
call	_put
add	esp,4
pop	ecx
mov	esp, ebp
pop	ebp
ret
_asm_main ENDP	; main
_TEXT	ENDS
_TEXT	SEGMENT
B$my:
;  Line: 11
push	ebp
mov	ebp, esp
sub	esp, 4
;  Line: 15
mov	eax, [ebp +12]
mov	[ecx +4], eax
;  Line: 16
mov	eax, [ecx +4]
push	ecx
push	eax
call	_put
add	esp,4
pop	ecx
;  Line: 18
mov	eax, 555
push	eax
mov	eax, [ecx +4]
mov	edx, eax
pop	eax
add	eax, edx
mov	[ecx +8], eax
;  Line: 19
mov	eax, [ecx +8]
push	ecx
push	eax
call	_put
add	esp,4
pop	ecx
mov	eax, [ebp +12]
mov	esp, ebp
pop	ebp
ret
_TEXT	ENDS
END 
