; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

	TITLE	C:\Users\nat\scratch\test.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_asm_main
EXTRN	_put:PROC
; Function compile flags: /Odtp
_TEXT	SEGMENT
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_asm_main PROC
; File c:\users\nat\scratch\test.c
; Line 6
	push	ebp
	mov	ebp, esp
; Line 7
	push	42
	call	_put
	add	esp, 4
; Line 8
	pop	ebp
	ret	0
_asm_main ENDP
_TEXT	ENDS
END
