; Listing generated by MuhammadUsman Non-optimizing Compiler Version <>

TITLE	blah.asm

	.686P 
	.XMM  
	include listing.inc 
	.model	flat 

INCLUDELIB LIBCMT 
INCLUDELIB OLDNAMES 

PUBLIC	_asm_main 
EXTRN	_put:PROC 
EXTRN	_get:PROC 
EXTRN  _mjmalloc:PROC 

_TEXT	SEGMENT 
_argc$ = 8                       ; size = 4 
_argv$ = 12                      ; size = 4 

_asm_main PROC
; Line 3
push	ebp
mov		ebp, esp
