package AST.Visitor;

import sun.reflect.generics.reflectiveObjects.NotImplementedException;

import java.io.FileWriter;

/**
 * Created by Muhammad on 6/7/2014.
 */
public class CGHelper {
    private static final String m_fileName = "blah.asm";
    private static FileWriter f = null;
    private static boolean init = false;

    public void initWriter()
    {
        try {
            f = new FileWriter(m_fileName);
            init = true;
        }
        catch(Exception e)
        {
            System.out.println("ERROR: failed to create file: " + m_fileName.toString());
        }

    }

    public void gen(String s)
    {
        System.out.print(s);
        if (init) {
            try {
                f.write(s);
                f.flush();
            }
            catch (Exception e) {
                System.out.println("ERROR: failed to write file: " + m_fileName.toString());
            }
        }
    }
    private void genTitle(String s)
    {
        gen("TITLE\t" + s.toString());
        gen("\r\n");
    }

    public void genCommentLine(String s)
    {
        gen("; " + s.toString());
        gen("\r\n");
    }

    public void genAsmPreamble()
    {
        genCommentLine("Listing generated by MuhammadUsman Non-optimizing Compiler Version <>");
        gen("\r\n");
        genTitle(m_fileName);
        gen("\r\n");
        gen(
            "\t.686P \r\n" +
            "\t.XMM  \r\n" +
            "\tinclude listing.inc \r\n" +
            "\t.model	flat \r\n" +
            "\r\n" +
            "INCLUDELIB LIBCMT \r\n" +
            "INCLUDELIB OLDNAMES \r\n" +
            "\r\n" +
            "PUBLIC	_asm_main \r\n" +
            "EXTRN	_put:PROC \r\n" +
            "EXTRN  _get:PROC \r\n" +
            "EXTRN  _mjmalloc:PROC \r\n" +
            "\r\n"
        );
    }

    public void genCallerProlog(int [] Args, String funcName)
    {
        //
        // push args right to left (decrement stack)
        // call (note that the hardware will push the return address (i.e. eip) into the stack then do the jump for u)
        //
        for (int i = Args.length; i > 0; i--) {
            gen("push\t" + Integer.toString(Args[i-1]));
            gen("\r\n");
        }
        gen("call\t"+funcName.toString());
        gen("\r\n");
    }
    public void genCallerEpilog(int cbArgs)
    {
        //
        // pop args (simply increment stack by total number of args size)
        // return value (if any) will be in eax. store if needed from eax to memory[ebp+offset-n]
        //
        if (cbArgs > 0) {
            gen("add\t\tesp, " + Integer.toString(cbArgs));
            gen("\r\n");
        }
    }

    public void genCalleeProlog(int cbTotalLocals)
    {
        gen("push\tebp");
        gen("\r\n");
        gen("mov\t\tebp, esp");
        gen("\r\n");
        if (cbTotalLocals != 0) {
            gen("sub\t\tesp, " + Integer.toString(cbTotalLocals));
            gen("\r\n");
        }
    }

    public void genCalleeEpilog()
    {
        gen("mov\t\tesp, ebp");
        gen("\r\n");
        gen("pop\t\tebp");
        gen("\r\n");
        gen("ret");
        gen("\r\n");
    }

    public void genAsmPostamble()
    {
        gen(
            "_TEXT	ENDS \r\n" +
            "END \r\n"
        );
    }
}
